# Specify the docker image to use (only used if using docker runners)
# See: http://doc.gitlab.com/ee/ci/docker/using_docker_images.html
image: debian:stable-slim

# Define commands that run before each job's script
before_script:
  - apt-get update
  - apt-get install -y make gcc g++ cmake

compile:
  script:
    - cd AStyle/
    - mkdir build_local
    - cmake .. && make
    - cd ../../AStyleTest/regression-sh/
    # Verify that our compiled app works properly with a custom "test" script
    - bash ./run_tests.sh